version: '3.1'

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WS
    ports:
      - "5432:5432"
    volumes:
      - /path/on/host:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "8080:8080"
