name: Code Inspection

on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven build
        run: mvn -B clean install -DskipTests

      - name: Run SpotBugs
        run: mvn -B com.github.spotbugs:spotbugs-maven-plugin:4.8.1.0:check

      - name: Run PMD
        run: mvn -B org.apache.maven.plugins:maven-pmd-plugin:3.15.0:check

      - name: Run OWASP Dependency Check
        run: mvn -B org.owasp:dependency-check-maven:8.4.2:check
