name: Code Inspection

on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven build
        run: mvn -B clean install -DskipTests

      - name: Run SpotBugs
        id: spotbugs
        run: mvn -B com.github.spotbugs:spotbugs-maven-plugin:4.8.1.0:check

      - name: Run PMD
        id: pmd
        run: mvn -B org.apache.maven.plugins:maven-pmd-plugin:3.15.0:check

      - name: Run OWASP Dependency Check
        id: owasp-check
        run: mvn -B org.owasp:dependency-check-maven:8.4.2:check

      - name: Create Issue on Failure
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_body = `
              ## Code Inspection Failures
              - SpotBugs: ${process.env.SPOTBUGS_RESULT}
              - PMD: ${process.env.PMD_RESULT}
              - OWASP Dependency Check: ${process.env.OWASP_CHECK_RESULT}
            `;
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Code Inspection Failure',
              body: issue_body
            });
            core.setFailed("Code inspection failed and issue was created.");
            env:
            SPOTBUGS_RESULT: ${{ steps.spotbugs.outcome == 'failure' ? 'SpotBugs failed' : 'SpotBugs passed' }}
            PMD_RESULT: ${{ steps.pmd.outcome == 'failure' ? 'PMD failed' : 'PMD passed' }}
            OWASP_CHECK_RESULT: ${{ steps.owasp-check.outcome == 'failure' ? 'OWASP Dependency Check failed' : 'OWASP Dependency Check passed' }}
