name: Issue to Project Board Automation
on:
  issues:
    types: [open]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Projeto de Testes de Software - 2023
          column: Issues
          repo-token: ${{ secrets.GITHUB_TOKEN }}

