name: Java CI with JMeter

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - main
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          echo "JMETER_HOME=$PWD/apache-jmeter-5.6.2" >> $GITHUB_ENV
          echo "$PWD/apache-jmeter-5.6.2/bin" >> $GITHUB_PATH
      

      - name: Start Spring Boot App
        run: |
          mvn spring-boot:run -Dspring-boot.run.profiles=test &
          SPRING_PID=$!
          sleep 10

      - name: Run JMeter Tests
        run: |
          jmeter -n -t ./jmeter/academico.jmx -l ./jmeter/results.csv

      - name: Analyze JMeter Results
        run: |
          if [ -f ./jmeter/results.csv ]; then
            echo "Analyzing JMeter results..."
            success_count=0
            failure_count=0
      
            while IFS=',' read -r timeStamp elapsed label responseCode responseMessage threadName dataType success failureMessage bytes sentBytes grpThreads allThreads URL latency idleTime connect
            do
              echo "Reading line: $label, Success: $success"
              if [ "$success" = "true" ]; then
                  ((success_count++))
              elif [ "$success" = "false" ]; then
                  ((failure_count++))
              else
                  echo "Unexpected format in results.csv"
                  exit 1
              fi
            done < ./jmeter/results.csv
      
            echo "Análise dos Resultados do JMeter:"
            echo "Testes bem-sucedidos: $success_count"
            echo "Testes com falha: $failure_count"
      
            if [ $failure_count -ne 0 ]; then
              echo "Foram encontradas falhas nos testes."
              exit 1
            fi
          else
            echo "JMeter results file not found."
            exit 1
          fi


      - name: Stop Spring Boot App
        run: |
          if [ -n "$SPRING_PID" ]; then
            kill $SPRING_PID || echo "Spring Boot app was not running."
          else
            echo "No PID found for Spring Boot app."
          fi
