name: Java CI with JMeter

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - main
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          echo "JMETER_HOME=$PWD/apache-jmeter-5.6.2" >> $GITHUB_ENV
          echo "$PWD/apache-jmeter-5.6.2/bin" >> $GITHUB_PATH
      

      - name: Start Spring Boot App
        run: |
          mvn spring-boot:run -Dspring-boot.run.profiles=test &
          SPRING_PID=$!
          sleep 10

      - name: Run JMeter Tests
        run: |
          jmeter -Jjmeter.save.saveservice.output_format=xml -n -t ./jmeter/academico.jmx -l ./jmeter/results.xml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Analyze JMeter XML Results
        run: |
          python ./analyze_jmeter_results.py

      - name: Stop Spring Boot App
        run: |
          if [ -n "$SPRING_PID" ]; then
            kill $SPRING_PID || echo "Spring Boot app was not running."
          else
            echo "No PID found for Spring Boot app."
          fi
