name: Test JMeter Action

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - main
      - develop
      - master

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Report Directory
        run: mkdir -p other_reports/

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: tests/academico.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - name: Run JMeter Action on other tests
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: other-tests/
          outputReportsFolder: other_reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results-other
          path: other_reports/

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: |
            summary_report.csv
            another_result_file.csv

      - name: Summarize JMeter Test Results
        run: |
          echo "Sumário dos Resultados do Teste:"
          [ -f reports/summary_report.csv ] && awk -F',' '{if(NR>1)print "Tempo de Resposta: "$2" ms, Status: "$4}' reports/summary_report.csv || echo "Nenhum relatório encontrado em reports/summary_report.csv"
          [ -f other_reports/another_result_file.csv ] && awk -F',' '{if(NR>1)print "Tempo de Resposta: "$2" ms, Status: "$4}' other_reports/another_result_file.csv || echo "Nenhum relatório encontrado em other_reports/another_result_file.csv"
